# Generated by Django 2.1 on 2018-08-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0004_auto_20180804_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samu',
            name='x_coordinate',
            field=models.DecimalField(decimal_places=30, max_digits=30),
        ),
        migrations.AlterField(
            model_name='samu',
            name='y_coordinate',
            field=models.DecimalField(decimal_places=30, max_digits=30),
        ),
    ]
