# Generated by Django 2.1 on 2018-09-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0012_hospitais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRef', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=500)),
                ('objetivo', models.CharField(max_length=500)),
                ('tipo', models.CharField(max_length=100)),
                ('coordinateX', models.DecimalField(decimal_places=10, max_digits=10)),
                ('coordinateY', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRef', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('municipio', models.CharField(max_length=100)),
                ('coordinateX', models.DecimalField(decimal_places=10, max_digits=10)),
                ('coordinateY', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
