# Generated by Django 2.1 on 2018-09-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0014_auto_20180904_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='coordinateX',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='coordinateY',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='unidadesaude',
            name='coordinateX',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='unidadesaude',
            name='coordinateY',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
    ]
