# Generated by Django 2.1 on 2018-09-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0016_auto_20180904_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='unit',
            field=models.ManyToManyField(to='saude.UnidadeSaude'),
        ),
    ]
